import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ADMIN_ID = int(os.getenv("ADMIN_ID", "0"))
KURS_ISHLARI_CHANNEL_ID = os.getenv("KURS_ISHLARI_CHANNEL_ID", "")
MAQOLALAR_CHANNEL_ID = os.getenv("MAQOLALAR_CHANNEL_ID", "")
TOLOV_TASDIQLASH_CHANNEL_ID = os.getenv("TOLOV_TASDIQLASH_CHANNEL_ID", "")

DEFAULT_KURS_ISH_PRICE = 25000
DEFAULT_MAQOLA_PRICE = 20000
DEFAULT_REFERAL_BONUS = 5000
